# Generated by Django 5.1 on 2024-08-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_category_slug_services_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolios/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
