# Generated by Django 5.1 on 2024-08-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_discription_portfolio_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
    ]
