# Generated by Django 5.1 on 2024-11-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
